apiVersion: v1
kind: Pod
metadata:
  name: firstpod
  labels:
    app: frontend
    team: Developer
    group: Cloud-Solutions
spec:
  containers:
  - name: nginx
    image: nginx:latest
    ports:
    - containerPort: 80